# Change these first
owner: r0manu3l # Your GitHub organization or username, where this repository lives
repo: inswhub # The name of this repository

sites:
  - name: Business Portal Dashboard
    url: https://dashboard-ish.apps.ins.inswhub.com/login
  - name: Business Portal Backend
    url: $BP_BACKEND
  - name: Authorization Server
    url: $AUTH_MANG
  - name: Authorization Sever 2
    url: $AUTH_TENANT
  - name: Developer Portal
    url: $DEV_PORTAL
  - name: Partners Sandbox
    url: $PARNERS_URL
    headers:
      - "apikey: $API_KEY_SANDBOX"
  - name: Partners Production
    url: $PARNERS_URL
    headers:
      - "apikey: $API_KEY_PRODUCTION"
  - name: Page Not Exist
    url: http://www.notexist.com
 
assignees: # Users to assign downtime issues (optional)
  - r0manu3l
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /inswhub
  logoUrl: https://inswitchpublic2.s3.amazonaws.com/inswitch_logo.png
  favicon: https://inswitchpublic2.s3.amazonaws.com/Favicon_blue.png
  name: Inswhub Platform
  introTitle: "**inswhub** Embedded Finance."
  introMessage: Making any Company a Fintech Company
  #navbar:
    #- title: Status
      #href: /
    #- title: GitHub
      #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
